package compiler2;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)

import java.util.ArrayList;
import java.util.Arrays;

//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final String digits = "0123456789.";
  public static final int SHORT = 4;
  public static final int IDENTIFIER = 98;
  public static final int ANDEQ = 90;
  public static final int GT = 70;
  public static final int IMPLEMENTS = 36;
  public static final int CONST = 101;
  public static final int STRICTFP = 100;
  public static final int NOTEQ = 75;
  public static final int PLUSEQ = 85;
  public static final int RBRACK = 11;
  public static final int CATCH = 55;
  public static final int COMMA = 15;
  public static final int RBRACE = 17;
  public static final int THROW = 53;
  public static final int RPAREN = 20;
  public static final int LBRACK = 10;
  public static final int LT = 69;
  public static final int ANDAND = 79;
  public static final int OROR = 80;
  public static final int DOUBLE = 9;
  public static final int LBRACE = 16;
  public static final int TRANSIENT = 32;
  public static final int LPAREN = 19;
  public static final int XOREQ = 91;
  public static final int PROTECTED = 25;
  public static final int INTEGER_LITERAL = 93;
  public static final int NOT = 63;
  public static final int FINAL = 29;
  public static final int FLOAT = 8;
  public static final int GOTO = 102;
  public static final int URSHIFTEQ = 89;
  public static final int PACKAGE = 22;
  public static final int COMP = 62;
  public static final int EQ = 18;
  public static final int BOOLEAN_LITERAL = 95;
  public static final int MOD = 65;
  public static final int CLASS = 34;
  public static final int SUPER = 40;
  public static final int ABSTRACT = 28;
  public static final int NATIVE = 30;
  public static final int LONG = 6;
  public static final int PLUS = 60;
  public static final int QUESTION = 81;
  public static final int WHILE = 48;
  public static final int EXTENDS = 35;
  public static final int INTERFACE = 41;
  public static final int CHAR = 7;
  public static final int BOOLEAN = 2;
  public static final int SWITCH = 44;
  public static final int DO = 47;
  public static final int FOR = 49;
  public static final int RSHIFTEQ = 88;
  public static final int VOID = 37;
  public static final int DIV = 64;
  public static final int PUBLIC = 24;
  public static final int RETURN = 52;
  public static final int MULT = 14;
  public static final int ELSE = 43;
  public static final int TRY = 54;
  public static final int GTEQ = 72;
  public static final int BREAK = 50;
  public static final int DOT = 12;
  public static final int INT = 5;
  public static final int NULL_LITERAL = 99;
  public static final int THROWS = 38;
  public static final int STRING_LITERAL = 97;
  public static final int EQEQ = 74;
  public static final int EOF = 0;
  public static final int SEMICOLON = 13;
  public static final int THIS = 39;
  public static final int DEFAULT = 46;
  public static final int MULTEQ = 82;
  public static final int IMPORT = 23;
  public static final int MINUS = 61;
  public static final int LTEQ = 71;
  public static final int OR = 78;
  public static final int error = 1;
  public static final int URSHIFT = 68;
  public static final int SYNCHRONIZED = 31;
  public static final int DIVEQ = 83;
  public static final int LSHIFTEQ = 87;
  public static final int FINALLY = 56;
  public static final int CONTINUE = 51;
  public static final int INSTANCEOF = 73;
  public static final int IF = 42;
  public static final int MODEQ = 84;
  public static final int MINUSMINUS = 59;
  public static final int COLON = 21;
  public static final int CHARACTER_LITERAL = 96;
  public static final int OREQ = 92;
  public static final int VOLATILE = 33;
  public static final int CASE = 45;
  public static final int PLUSPLUS = 58;
  public static final int NEW = 57;
  public static final int RSHIFT = 67;
  public static final int BYTE = 3;
  public static final int AND = 76;
  public static final int PRIVATE = 26;
  public static final int STATIC = 27;
  public static final int LSHIFT = 66;
  public static final int XOR = 77;
  public static final int FLOATING_POINT_LITERAL = 94;
  public static final int MINUSEQ = 86;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "PACKAGE",
  "IMPORT",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "ABSTRACT",
  "FINAL",
  "NATIVE",
  "SYNCHRONIZED",
  "TRANSIENT",
  "VOLATILE",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "VOID",
  "THROWS",
  "THIS",
  "SUPER",
  "INTERFACE",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "THROW",
  "TRY",
  "CATCH",
  "FINALLY",
  "NEW",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "INSTANCEOF",
  "EQEQ",
  "NOTEQ",
  "AND",
  "XOR",
  "OR",
  "ANDAND",
  "OROR",
  "QUESTION",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "URSHIFTEQ",
  "ANDEQ",
  "XOREQ",
  "OREQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL",
  "STRICTFP",
  "CONST",
  "GOTO"
  };
  static ArrayList<String> KEYWORDS2 = new ArrayList<>(Arrays.asList(terminalNames));
  public static int getID(String s){
      switch (s){
        case "IF":return IF;
        case "FOR":return FOR;
        case "BOOLEAN":return BOOLEAN;
        case "STRING":return STRING_LITERAL;
        case "WHIEL":return WHILE;
        case "ELSE":return ELSE;
        case "INT":return INT;
        case "FLOAT":return FLOAT;
        case "DO":return DO;
        case "CLASS":return CLASS;
        case "String":return STRING_LITERAL;
        default:return 0;
      }
//      return 0;
  }
}

